/*Tables creation following the physical model*/

CREATE TABLE education(
    EDLVL_ID SERIAL PRIMARY KEY,
    ED_LVL VARCHAR(50)
);

CREATE TABLE employee(
    EMP_ID VARCHAR(10) PRIMARY KEY,
    EMP_NM VARCHAR(50),
    EMAIL VARCHAR(50),
    HIRE_DT DATE,
    EDLVL_ID INT REFERENCES education(EDLVL_ID)
);

CREATE TABLE department(
    DEPT_ID SERIAL PRIMARY KEY,
    DEPT_NM VARCHAR(50)
);

CREATE TABLE job(
    JOB_ID SERIAL PRIMARY KEY,
    JOB_NM VARCHAR(50)
);

CREATE TABLE state(
    STATE_ID SERIAL PRIMARY KEY,
    STATE_NM VARCHAR(50)
);

CREATE TABLE city(
    CITY_ID SERIAL PRIMARY KEY,
    CITY_NM VARCHAR(50),
    STATE_ID INT REFERENCES state(STATE_ID)
);

CREATE TABLE location(
    LOC_ID SERIAL PRIMARY KEY,
    LOC_NM VARCHAR(50)
);

CREATE TABLE address(
    ADD_ID SERIAL PRIMARY KEY,
    ADD_NM VARCHAR(100),
    CITY_ID INT REFERENCES city(CITY_ID),
    LOC_ID INT REFERENCES location(LOC_ID)
);

CREATE TABLE jobhist(
    JH_ID SERIAL PRIMARY KEY,
    EMP_ID VARCHAR(10) REFERENCES employee(EMP_ID),
    JOB_ID INT REFERENCES job(JOB_ID),
    DEPT_ID INT REFERENCES department(DEPT_ID),
    ADD_ID INT REFERENCES address(ADD_ID),
    MAN_ID VARCHAR(10) REFERENCES employee(EMP_ID),
    START_DT DATE,
    END_DT DATE
);

CREATE TABLE salary(
    SAL_ID SERIAL PRIMARY KEY,
    JH_ID INT REFERENCES jobhist(JH_ID),
    SALARY NUMERIC
);

